### ISSUE TITLE
Wrong seed data

### ISSUE THREAD

**Issue by vangelov** [vietthang/hapi-boilerplate#1]
Hello, 
First let me say I think this is one of the best boilerplates I've found. 
I noticed, however, the seed data contains some errors. 

- For some reason the knex insert method doesn't return the id, which makes all resourceIds variables be 0. 
- The rows for the Content table are missing the name which is a required property.

The second problem is easy to solve. The first can be fixed by creating the UUID before the insert. The problem is the original code should work, at least according to the knex docs. Are you able to reproduce the first issue?

**Comment by vietthang** [comment]
Thank you very much for your feedback.  I've just checked with 2 issues you mentioned.

- About the knex issue. I dig into knex source code a bit and saw it seems like the problem with mysql dialect, somehow the `insertId` return 0. I will submit an issue for them later. For now, I fixed it as you suggested. (create UUID before insert).
- Fixed the missing title in Content data also.

**Comment by vangelov** [comment]
Thanks!
